import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const CATEGORIES = {
  homepage: ["loans", "offers", "general", "properties", "referrals", "core-concepts"],
  homepage_ad: [
    "sponsor",
    "personal-finance",
    "business-finance",
    "cards-and-rewards",
    "insurance-protection",
    "verified-property",
  ],
  financial_services: [
    "personal-loan",
    "business-loan",
    "home-loan",
    "loan-against-property",
    "car-loan",
    "vehicle-loan",
    "education-loan",
    "school-funding",
    "secured-loans",
    "od-and-dod",
    "project-funding",
    "life-insurance",
    "health-insurance",
    "property-insurance",
    "travel-insurance",
    "credit-cards",
  ],
  properties: [
    "individual-house",
    "standalone-apartment",
    "gated-community-apartment",
    "villa",
    "locked-space",
    "unlocked-space",
    "plot",
    "farmland",
    "agriland",
    "apartments",
    "houses",
    "villas",
    "plots-land",
    "commercial",
    "offers",
    "guidance-general",
  ],
} as const;

// Explicit per-placement geometry, deliberately not a ternary: a ternary
// silently drops a new placement into the else-branch and then demands the
// wrong artwork size. Indexing this map means a new placement fails loudly.
const EXPECTED_SIZE: Record<keyof typeof CATEGORIES, { width: number; height: number }> = {
  homepage: { width: 1440, height: 800 },
  homepage_ad: { width: 960, height: 540 },
  financial_services: { width: 1440, height: 576 },
  properties: { width: 1440, height: 576 },
};

function webpSize(bytes: Buffer): { width: number; height: number } {
  const chunk = bytes.toString("ascii", 12, 16);
  if (chunk === "VP8 ") {
    return {
      width: bytes.readUInt16LE(26) & 0x3fff,
      height: bytes.readUInt16LE(28) & 0x3fff,
    };
  }
  if (chunk === "VP8X") {
    return {
      width: 1 + bytes.readUIntLE(24, 3),
      height: 1 + bytes.readUIntLE(27, 3),
    };
  }
  throw new Error(`Unsupported WEBP chunk ${chunk}`);
}

describe("bundled banner template artwork", () => {
  it("contains one bounded, placement-sized WEBP for each governed category", () => {
    const files = Object.entries(CATEGORIES).flatMap(([placement, categories]) =>
      categories.map((category) => ({
        file: join(process.cwd(), "public", "banner-templates", placement, `${category}.webp`),
        expectedSize: EXPECTED_SIZE[placement as keyof typeof CATEGORIES],
      })),
    );
    expect(files).toHaveLength(44);
    for (const { file, expectedSize } of files) {
      expect(statSync(file).size).toBeGreaterThan(0);
      expect(statSync(file).size).toBeLessThanOrEqual(2 * 1024 * 1024);
      const bytes = readFileSync(file);
      expect(bytes.toString("ascii", 0, 4)).toBe("RIFF");
      expect(bytes.toString("ascii", 8, 12)).toBe("WEBP");
      expect(webpSize(bytes)).toEqual(expectedSize);
    }
  });

  it("contains no ungoverned files or exact duplicate artwork", () => {
    const hashes = new Map<string, string[]>();

    for (const [placement, categories] of Object.entries(CATEGORIES)) {
      const directory = join(process.cwd(), "public", "banner-templates", placement);
      const actualFiles = readdirSync(directory).sort();
      const expectedFiles = categories.map((category) => `${category}.webp`).sort();
      expect(actualFiles).toEqual(expectedFiles);

      for (const file of actualFiles) {
        const hash = createHash("sha256")
          .update(readFileSync(join(directory, file)))
          .digest("hex");
        hashes.set(hash, [...(hashes.get(hash) ?? []), `${placement}/${file}`]);
      }
    }

    expect([...hashes.values()].filter((files) => files.length > 1)).toEqual([]);
  });
});

describe("generated campaign starter artwork", () => {
  it("ships optimized, wide WEBP assets for the Sub Admin Media Library", () => {
    const files = [
      "home-loan-journey.webp",
      "verified-residence.webp",
      "rewards-and-savings.webp",
    ];
    const hashes = new Set<string>();
    for (const file of files) {
      const path = join(process.cwd(), "public", "banner-templates", "starter", file);
      const bytes = readFileSync(path);
      const size = webpSize(bytes);
      expect(statSync(path).size).toBeLessThanOrEqual(500 * 1024);
      expect(size.width).toBeGreaterThanOrEqual(1200);
      expect(size.width / size.height).toBeGreaterThanOrEqual(1.9);
      expect(bytes.toString("ascii", 0, 4)).toBe("RIFF");
      expect(bytes.toString("ascii", 8, 12)).toBe("WEBP");
      hashes.add(createHash("sha256").update(bytes).digest("hex"));
    }
    expect(hashes.size).toBe(files.length);
  });
});

// Dashboard banners and dashboard offers have no governed template catalogue --
// they draw on Media Library assets. These bundled files are the seed for that
// library, generated by scripts/build_dashboard_artwork.py and registered by
// migration b7c9d1e3f5a8, so their names, geometry and uniqueness are a
// contract in both directions.
const DASHBOARD_ARTWORK = {
  dashboard: {
    size: { width: 1296, height: 720 },
    keys: [
      "loan-progress",
      "document-upload",
      "referral-boost",
      "profile-complete",
      "property-saved",
      "agent-payout",
    ],
  },
  dashboard_offer: {
    size: { width: 1120, height: 490 },
    keys: [
      "cashback",
      "festive",
      "fee-waiver",
      "partner-deal",
      "interest-cut",
      "travel",
      "shopping",
      "insurance",
    ],
  },
} as const;

describe("seeded dashboard and offer artwork", () => {
  it("ships one correctly shaped WEBP per seeded category", () => {
    for (const [directory, { size, keys }] of Object.entries(DASHBOARD_ARTWORK)) {
      const path = join(process.cwd(), "public", "banner-templates", directory);
      expect(readdirSync(path).sort()).toEqual(keys.map((key) => `${key}.webp`).sort());
      for (const key of keys) {
        const file = join(path, `${key}.webp`);
        const bytes = readFileSync(file);
        expect(statSync(file).size).toBeLessThanOrEqual(500 * 1024);
        expect(bytes.toString("ascii", 0, 4)).toBe("RIFF");
        expect(bytes.toString("ascii", 8, 12)).toBe("WEBP");
        expect(webpSize(bytes)).toEqual(size);
      }
    }
  });

  it("holds no duplicate artwork anywhere under banner-templates", () => {
    const hashes = new Map<string, string[]>();
    const root = join(process.cwd(), "public", "banner-templates");
    for (const directory of readdirSync(root)) {
      for (const file of readdirSync(join(root, directory))) {
        const hash = createHash("sha256")
          .update(readFileSync(join(root, directory, file)))
          .digest("hex");
        hashes.set(hash, [...(hashes.get(hash) ?? []), `${directory}/${file}`]);
      }
    }
    expect([...hashes.values()].filter((files) => files.length > 1)).toEqual([]);
  });
});
