import {
  ArrowLeftRight,
  BadgePercent,
  Banknote,
  BarChart3,
  Bookmark,
  Building2,
  CalendarCheck,
  CarFront,
  ClipboardCheck,
  ClipboardList,
  Database,
  FileCheck2,
  FilePlus2,
  FileText,
  FolderClosed,
  Gift,
  Headset,
  House,
  IndianRupee,
  Landmark,
  Megaphone,
  MessageSquare,
  PhoneCall,
  Scale,
  ScrollText,
  ShieldCheck,
  SlidersHorizontal,
  Telescope,
  UserPlus,
  UserRound,
} from "lucide-react";

// One semantic icon vocabulary for the authenticated application. Navigation,
// page headers, metrics, and quick actions import from this map so the same
// concept never changes pictogram between role dashboards.
export const DASHBOARD_ICONS = {
  home: House,
  explore: Telescope,
  applyForLoan: FilePlus2,
  loanApplications: Landmark,
  loanMedia: FolderClosed,
  compare: Scale,
  loanOfficer: UserRound,
  bookmarks: Bookmark,
  enquiries: MessageSquare,
  siteVisits: CalendarCheck,
  agent: UserRound,
  propertyListings: Building2,
  propertySubmit: FilePlus2,
  transactions: ArrowLeftRight,
  referrals: Gift,
  leads: PhoneCall,
  tasks: ClipboardList,
  vehicleArrangements: CarFront,
  earnings: IndianRupee,
  banners: Megaphone,
  offers: BadgePercent,
  websiteContent: FileText,
  loanConfiguration: SlidersHorizontal,
  propertyDeals: Building2,
  listingApprovals: ClipboardCheck,
  documentVerification: FileCheck2,
  usersAndStaff: UserPlus,
  agentApplications: UserRound,
  supportTickets: Headset,
  accessControl: ShieldCheck,
  payouts: Banknote,
  commissions: IndianRupee,
  feeCashbacks: BadgePercent,
  broadcast: Megaphone,
  analytics: BarChart3,
  auditLog: ScrollText,
  operationalRecords: Database,
} as const;
