# ruff: noqa: E501
"""Exhaustive FR-2.2 Admin operational-coverage contract.

This registry is an audit artifact, not an authorization mechanism. API
dependencies, service checks, grants, and PostgreSQL RLS remain authoritative.
The contract makes every mapped table's intended Admin visibility, mutation,
and audit posture explicit so new tables cannot silently fall outside the
FR-2.2 review or acquire an unsafe generic-CRUD interpretation.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass


class CoverageState(enum.StrEnum):
    COVERED = "covered"
    GAP = "gap"
    PROTECTED = "protected"


class AdminViewMode(enum.StrEnum):
    FULL = "full"
    MINIMIZED = "minimized"
    AGGREGATE = "aggregate"
    AUDIT_ONLY = "audit_only"
    PROHIBITED = "prohibited"


class AdminUpdateMode(enum.StrEnum):
    CONFIGURATION_COMMAND = "configuration_command"
    STATUS_COMMAND = "status_command"
    WORKFLOW_COMMAND = "workflow_command"
    APPEND_ONLY = "append_only"
    IMMUTABLE = "immutable"
    SERVICE_MANAGED = "service_managed"
    PROHIBITED = "prohibited"


class DataSensitivity(enum.StrEnum):
    CONTACT_PII = "contact_pii"
    IDENTITY_PII = "identity_pii"
    KYC = "kyc"
    FINANCIAL = "financial"
    PRIVATE_MEDIA = "private_media"
    PRECISE_LOCATION = "precise_location"
    SESSION_SECRET = "session_secret"
    PUSH_SECRET = "push_secret"
    STORAGE_KEY = "storage_key"
    AUDIT_METADATA = "audit_metadata"


@dataclass(frozen=True, slots=True)
class AdminCoverageEntry:
    domain: str
    sensitivity: frozenset[DataSensitivity]
    view_mode: AdminViewMode
    view_coverage: CoverageState
    update_mode: AdminUpdateMode
    update_coverage: CoverageState
    audit_coverage: CoverageState
    api_surfaces: tuple[str, ...]
    ui_surfaces: tuple[str, ...]
    rls_expectation: str
    audit_expectation: str
    rationale: str
    gap: str | None = None


def _entry(
    *,
    domain: str,
    view_mode: AdminViewMode,
    view_coverage: CoverageState,
    update_mode: AdminUpdateMode,
    update_coverage: CoverageState,
    audit_coverage: CoverageState,
    api_surfaces: tuple[str, ...] = (),
    ui_surfaces: tuple[str, ...] = (),
    sensitivity: tuple[DataSensitivity, ...] = (),
    rls_expectation: str,
    audit_expectation: str,
    rationale: str,
    gap: str | None = None,
) -> AdminCoverageEntry:
    return AdminCoverageEntry(
        domain=domain,
        sensitivity=frozenset(sensitivity),
        view_mode=view_mode,
        view_coverage=view_coverage,
        update_mode=update_mode,
        update_coverage=update_coverage,
        audit_coverage=audit_coverage,
        api_surfaces=api_surfaces,
        ui_surfaces=ui_surfaces,
        rls_expectation=rls_expectation,
        audit_expectation=audit_expectation,
        rationale=rationale,
        gap=gap,
    )


# Keep this exhaustive. The matching static test compares these keys with
# Base.metadata.tables. A CoverageState.GAP is an implementation finding; a
# PROTECTED state is an intentional least-privilege boundary, not missing CRUD.
ADMIN_OPERATIONAL_COVERAGE: dict[str, AdminCoverageEntry] = {
    "agent_applications": _entry(
        domain="Agent application and KYC review",
        sensitivity=(DataSensitivity.CONTACT_PII, DataSensitivity.KYC),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/agents",),
        ui_surfaces=("/dashboard/agents",),
        rls_expectation="Platform Admin reads and review commands require the admin role and platform scope.",
        audit_expectation="Approval and rejection append agent_approved or agent_rejected entries.",
        rationale="The review projection provides purpose-bound KYC access without returning storage internals.",
    ),
    "agent_profiles": _entry(
        domain="Active Agent identity and business-line profile",
        sensitivity=(DataSensitivity.IDENTITY_PII,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.STATUS_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/users", "/api/v1/admin/reports/agents"),
        ui_surfaces=("/dashboard/users", "/dashboard/analytics"),
        rls_expectation="Only platform Admin receives cross-line profile visibility; scoped roles retain line or owner filters.",
        audit_expectation="Agent creation/review and account status changes are appended to the business audit log.",
        rationale="User oversight and Agent reporting expose the operational profile; account status is the supported deactivation command.",
    ),
    "audit_log": _entry(
        domain="Append-only business audit history",
        sensitivity=(DataSensitivity.AUDIT_METADATA,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.APPEND_ONLY,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/audit-log",),
        ui_surfaces=("/dashboard/audit-log",),
        rls_expectation="Platform Admin may select; api_user has no UPDATE or DELETE grant.",
        audit_expectation="The row is the immutable audit evidence and corrections append a new row.",
        rationale="History must remain inspectable but never editable or deletable by Admin.",
    ),
    "auth_events": _entry(
        domain="Authentication and recovery security events",
        sensitivity=(DataSensitivity.CONTACT_PII, DataSensitivity.AUDIT_METADATA),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.APPEND_ONLY,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/operations/auth-events",),
        ui_surfaces=("/dashboard/operations",),
        rls_expectation="Only platform Admin may list the minimized projection; raw event rows stay append-only.",
        audit_expectation="The source rows are immutable authentication audit evidence.",
        rationale="The dedicated projection provides outcome and time oversight while omitting mobile, IP, user-agent, and detail fields.",
    ),
    "auth_users": _entry(
        domain="Authentication users and account lifecycle",
        sensitivity=(DataSensitivity.CONTACT_PII, DataSensitivity.IDENTITY_PII),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.STATUS_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/users",),
        ui_surfaces=("/dashboard/users",),
        rls_expectation="Only role=admin with platform_scope=true may list or change another operational account.",
        audit_expectation="Status and deletion commands record bounded reasons without contact values.",
        rationale="The Admin surface supports provision, suspend/reactivate, and deletion without arbitrary identity-field editing; deleted tombstone emails are redacted.",
    ),
    "bank_loan_type_availability": _entry(
        domain="Bank-to-loan-product availability",
        view_mode=AdminViewMode.FULL,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.CONFIGURATION_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/bank-availability",),
        ui_surfaces=("/dashboard/loan-config",),
        rls_expectation="Platform Admin owns configuration writes; public consumers receive only active derived choices.",
        audit_expectation="Every matrix update appends bank_availability_updated.",
        rationale="This is platform configuration with explicit typed commands and no delete workflow.",
    ),
    "banks": _entry(
        domain="Loan bank configuration",
        view_mode=AdminViewMode.FULL,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.CONFIGURATION_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/banks",),
        ui_surfaces=("/dashboard/loan-config",),
        rls_expectation="Platform Admin owns bank creation and status/configuration updates.",
        audit_expectation="Create and update commands append bank_created or bank_updated.",
        rationale="Typed configuration commands satisfy Admin control without generic row editing.",
    ),
    "banners": _entry(
        domain="Banner authoring, approval, and publication",
        view_mode=AdminViewMode.FULL,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/banners",),
        ui_surfaces=("/dashboard/banners",),
        rls_expectation="Platform Admin may manage any row; Sub Admin remains creator-scoped for delegated authoring.",
        audit_expectation="Material authoring and lifecycle transitions need append-only business audit events.",
        rationale=(
            "Admin authoring and approval exist, and every mutating transition now"
            " writes an append-only audit event: create/update/delete at the router,"
            " submit/approve/reject/archive in the service, and activate/expire in the"
            " scheduler job so scheduler-driven go-live is not an untraced gap."
        ),
    ),
    "banner_templates": _entry(
        domain="Banner artwork template catalogue and versioning",
        view_mode=AdminViewMode.FULL,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/banners/templates",),
        ui_surfaces=("/dashboard/banners",),
        rls_expectation=(
            "Sub Admin and Admin may read the catalogue; only platform Admin may"
            " insert or retire a version, and a database trigger makes a published"
            " version immutable so history cannot be rewritten in place."
        ),
        audit_expectation="Publishing a new template version needs an append-only audit event.",
        rationale=(
            "Templates carry no customer data — they are reviewed, text-free artwork"
            " plus a category label. Versioning is append-only: retiring a version"
            " clears `active` rather than mutating the row, and every publish records"
            " BANNER_TEMPLATE_VERSIONED."
        ),
    ),
    "bookmarks": _entry(
        domain="Client property bookmarks",
        view_mode=AdminViewMode.PROHIBITED,
        view_coverage=CoverageState.PROTECTED,
        update_mode=AdminUpdateMode.PROHIBITED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.PROTECTED,
        rls_expectation="Owner-only access remains authoritative; Admin receives no preference-level bypass.",
        audit_expectation="Bookmark contents are not a business-action audit surface.",
        rationale="A private Client preference has no legitimate Admin operational mutation or raw-inspection need.",
    ),
    "client_profiles": _entry(
        domain="Client line profiles",
        sensitivity=(DataSensitivity.IDENTITY_PII,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.SERVICE_MANAGED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/users",),
        ui_surfaces=("/dashboard/users",),
        rls_expectation="The minimized projection requires platform Admin; profile ownership and per-record line RLS stay unchanged.",
        audit_expectation="Creation/deletion follows identity lifecycle evidence; no arbitrary profile mutation is allowed.",
        rationale="The user list identifies distinct Loans and Real Estate profile records without exposing private profile facts.",
    ),
    "commissions": _entry(
        domain="Agent commission agreements and payout linkage",
        sensitivity=(DataSensitivity.FINANCIAL,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/commissions",),
        ui_surfaces=("/dashboard/commissions",),
        rls_expectation="Platform Admin has cross-line access; Agents retain own-earnings reads only.",
        audit_expectation="Entry, cancellation, payout approval, and settlement transitions are auditable.",
        rationale="Typed money commands preserve eligibility, caps, maker-checker, and ledger constraints.",
    ),
    "contact_share_links": _entry(
        domain="Employee contact-sharing invitations",
        sensitivity=(DataSensitivity.CONTACT_PII, DataSensitivity.SESSION_SECRET),
        view_mode=AdminViewMode.PROHIBITED,
        view_coverage=CoverageState.PROTECTED,
        update_mode=AdminUpdateMode.PROHIBITED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.PROTECTED,
        rls_expectation="Only the assigned Employee workflow and bypass cleanup may access token-hash rows.",
        audit_expectation="Policy changes and public validation remain PII-free; token hashes are never audit output.",
        rationale="Admin configures the governing field policy but must not browse or reuse individual invitation secrets.",
    ),
    "content_blocks": _entry(
        domain="Website content blocks",
        view_mode=AdminViewMode.FULL,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.GAP,
        api_surfaces=("/api/v1/content-blocks",),
        ui_surfaces=("/dashboard/content",),
        rls_expectation="Platform Admin may manage all content; Sub Admin remains creator-scoped.",
        audit_expectation="Create, correction, publish, and archive transitions require append-only history.",
        rationale="The current mutable row stores only latest state, so it cannot by itself provide historical auditing.",
        gap="Gap: content-block authoring and lifecycle transitions are not comprehensively represented in audit_log.",
    ),
    "enquiries": _entry(
        domain="Client property enquiries",
        sensitivity=(DataSensitivity.CONTACT_PII,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.APPEND_ONLY,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/operations/enquiries",),
        ui_surfaces=("/dashboard/operations",),
        rls_expectation="Platform Admin may read through RLS, while creation remains Client-owned and server-stamped.",
        audit_expectation="The enquiry is an append-only source record; corrections require a future explicit workflow, not mutation.",
        rationale="The paginated Admin projection omits contact identity and message fields while preserving workflow context.",
    ),
    "fee_cashbacks": _entry(
        domain="Processing-fee cashback agreements and payouts",
        sensitivity=(DataSensitivity.FINANCIAL,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/fee-cashbacks",),
        ui_surfaces=("/dashboard/fee-cashbacks",),
        rls_expectation="Platform Admin has cross-line control; Client exposure stays tied to the resulting ledger only.",
        audit_expectation="Entry, cancellation, payout, and settlement events are auditable.",
        rationale="The dedicated money workflow avoids arbitrary amount or ledger editing.",
    ),
    "field_visibility_config": _entry(
        domain="Role field-visibility configuration",
        view_mode=AdminViewMode.FULL,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.CONFIGURATION_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/field-visibility",),
        ui_surfaces=("/dashboard/access-control",),
        rls_expectation="Only platform Admin may write the closed server-owned catalogue.",
        audit_expectation="Every policy change appends field_visibility_updated without field values.",
        rationale="Closed keys and modes prevent arbitrary JSON-path policy creation.",
    ),
    "lead_activities": _entry(
        domain="Append-only Telecaller lead call activities",
        sensitivity=(DataSensitivity.CONTACT_PII,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.APPEND_ONLY,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/operations/lead-activities",),
        ui_surfaces=("/dashboard/operations",),
        rls_expectation="Platform Admin may select the minimized projection through RLS; only the assigned Telecaller may append activity rows.",
        audit_expectation="Each activity is immutable source evidence; corrections append another activity.",
        rationale="The operational history exposes dispositions and timing while withholding free-text call notes.",
    ),
    "lead_assignment_cursors": _entry(
        domain="Round-robin assignment cursor state",
        view_mode=AdminViewMode.AGGREGATE,
        view_coverage=CoverageState.PROTECTED,
        update_mode=AdminUpdateMode.SERVICE_MANAGED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.PROTECTED,
        rls_expectation="Only the row-locked assignment service and migration/diagnostic tests access cursor state.",
        audit_expectation="Lead-assigned business events, not raw cursor mutations, are the operational audit trail.",
        rationale="Manual cursor reads or edits could corrupt concurrency and assignment fairness.",
    ),
    "employee_assignment_cursors": _entry(
        domain="Round-robin Employee assignment cursor state",
        view_mode=AdminViewMode.AGGREGATE,
        view_coverage=CoverageState.PROTECTED,
        update_mode=AdminUpdateMode.SERVICE_MANAGED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.PROTECTED,
        rls_expectation="Only automatic assignment services and migration tests access cursor state.",
        audit_expectation="Employee work-assigned events, not raw cursor turns, are the audit trail.",
        rationale="Manual cursor access could corrupt cross-workflow fairness and concurrency.",
    ),
    "leads": _entry(
        domain="Loans and Real Estate lead records",
        sensitivity=(DataSensitivity.CONTACT_PII,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/leads",),
        ui_surfaces=("/dashboard/admin-leads",),
        rls_expectation="Platform Admin receives both-line access; Agent ownership and scoped-role predicates remain authoritative.",
        audit_expectation="Assignment, release, expiry, and reasoned detail corrections append safe events.",
        rationale="Named commands preserve immutable ownership, lifecycle cutoffs, and provenance.",
    ),
    "loan_applications": _entry(
        domain="Loan application progression",
        sensitivity=(DataSensitivity.FINANCIAL, DataSensitivity.IDENTITY_PII),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.GAP,
        api_surfaces=("/api/v1/admin/loans",),
        ui_surfaces=("/dashboard/loan-applications",),
        rls_expectation="Platform Admin can read and progress both-line applications; Client and staff paths stay owner/assignment scoped.",
        audit_expectation="Every Admin progression and material terms change needs append-only business history.",
        rationale="The forward-only status service is safe, but the mutable row preserves only current status and reason.",
        gap="Gap: Admin loan-application progress updates are not comprehensively represented in audit_log.",
    ),
    "loan_documents": _entry(
        domain="Client loan documents",
        sensitivity=(
            DataSensitivity.KYC,
            DataSensitivity.PRIVATE_MEDIA,
            DataSensitivity.STORAGE_KEY,
        ),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/document-verification",),
        ui_surfaces=("/dashboard/document-verification",),
        rls_expectation="Platform Admin may review; signed downloads are purpose-bound and raw object keys are not serialized.",
        audit_expectation="Verification and unverification append document audit events without file content or keys.",
        rationale="The unified verification workflow provides least-data document oversight.",
    ),
    "loan_txn_history": _entry(
        domain="Immutable loan transaction-term history",
        sensitivity=(DataSensitivity.FINANCIAL,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.APPEND_ONLY,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/operations/loan-transaction-history",),
        ui_surfaces=("/dashboard/operations",),
        rls_expectation="Platform Admin may select the minimized projection through RLS; assigned Telecallers append and nobody rewrites history.",
        audit_expectation="The immutable history rows are the source audit; corrections append a new row.",
        rationale="The operational history exposes immutable terms and attribution without creating edit authority.",
    ),
    "loan_types": _entry(
        domain="Loan product configuration",
        view_mode=AdminViewMode.FULL,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.CONFIGURATION_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/loan-types",),
        ui_surfaces=("/dashboard/loan-config",),
        rls_expectation="Platform Admin owns creation and active/configuration changes.",
        audit_expectation="Create and update commands append loan_type_created or loan_type_updated.",
        rationale="Config-driven product control is implemented without delete or developer intervention.",
    ),
    "mobile_change_requests": _entry(
        domain="Support-assisted mobile-number changes",
        sensitivity=(DataSensitivity.CONTACT_PII, DataSensitivity.IDENTITY_PII),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/mobile-change-requests",),
        ui_surfaces=("/dashboard/support-tickets",),
        rls_expectation="Platform Admin maker/checker rules and target exclusions are enforced at API, service, and RLS layers.",
        audit_expectation="Verification, completion, and rejection append PII-free audit events.",
        rationale="The structured workflow avoids arbitrary identity editing and revokes sessions atomically.",
    ),
    "notifications": _entry(
        domain="User notifications and Admin broadcasts",
        sensitivity=(DataSensitivity.IDENTITY_PII,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.APPEND_ONLY,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/notifications/admin/audit", "/api/v1/notifications/broadcast"),
        ui_surfaces=("/dashboard/audit-log", "/dashboard/broadcast"),
        rls_expectation="Platform Admin may inspect a minimized feed; recipient read state remains owner-controlled.",
        audit_expectation="Broadcast creation appends notification_broadcast; source notifications remain immutable except owner read state.",
        rationale="Oversight excludes recipient contact data and does not mutate another user's feed.",
    ),
    "offers": _entry(
        domain="Offer and promotion lifecycle",
        view_mode=AdminViewMode.FULL,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.GAP,
        api_surfaces=("/api/v1/offers",),
        ui_surfaces=("/dashboard/offers",),
        rls_expectation="Platform Admin may manage all rows; Sub Admin remains creator-scoped.",
        audit_expectation="Create, correction, schedule, activate, and archive commands need append-only history.",
        rationale="Current mutable records expose latest state but not a complete historical action trail.",
        gap="Gap: offer authoring and lifecycle transitions are not comprehensively represented in audit_log.",
    ),
    "payouts": _entry(
        domain="Outbound payout workflow",
        sensitivity=(DataSensitivity.FINANCIAL, DataSensitivity.CONTACT_PII),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/payouts",),
        ui_surfaces=("/dashboard/payouts",),
        rls_expectation="Platform Admin executes checker and reconciliation commands; delegated Sub Admin access stays create/list only.",
        audit_expectation="Approval, rejection, cheque lifecycle, reversal, and reconciliation append safe events.",
        rationale="Masked destinations and named commands preserve maker-checker, caps, idempotency, and ledger integrity.",
    ),
    "personalization_preferences": _entry(
        domain="Client personalization consent and coarse location",
        sensitivity=(DataSensitivity.PRECISE_LOCATION,),
        view_mode=AdminViewMode.PROHIBITED,
        view_coverage=CoverageState.PROTECTED,
        update_mode=AdminUpdateMode.PROHIBITED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.PROTECTED,
        rls_expectation="Owner-only preference access; Admin receives no raw coordinate or consent-override bypass.",
        audit_expectation="Consent timestamps remain on the owner record and audits/logs exclude coordinates.",
        rationale="Admin must not inspect or override private preference and location choices merely to satisfy FR-2.2 wording.",
    ),
    "properties": _entry(
        domain="Approved property listings",
        view_mode=AdminViewMode.FULL,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.STATUS_COMMAND,
        update_coverage=CoverageState.GAP,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/properties",),
        ui_surfaces=("/dashboard/property-review",),
        rls_expectation="Platform Admin sees active and inactive rows; status updates require platform Admin and preserve immutable line/media review facts.",
        audit_expectation="Publish/hide changes append property_listing_updated with a bounded reason.",
        rationale="Availability control exists, but reviewed listing facts have no reasoned correction command.",
        gap="Gap: Admin cannot correct approved listing facts through a typed, audited workflow while preserving submission and media provenance.",
    ),
    "property_deals": _entry(
        domain="Real Estate deal progression",
        sensitivity=(DataSensitivity.FINANCIAL, DataSensitivity.IDENTITY_PII),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.GAP,
        api_surfaces=("/api/v1/admin/property-deals",),
        ui_surfaces=("/dashboard/property-deals",),
        rls_expectation="Platform Admin can read and progress deals; Client and staff reads remain owner/assignment scoped.",
        audit_expectation="Every Admin progression and terms command needs append-only business history.",
        rationale="The status machine is controlled, but the mutable row retains only current status and reason.",
        gap="Gap: Admin property-deal progress and terms changes are not comprehensively represented in audit_log.",
    ),
    "property_media": _entry(
        domain="Approved property image and panorama media",
        sensitivity=(DataSensitivity.STORAGE_KEY,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.SERVICE_MANAGED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/properties",),
        ui_surfaces=("/dashboard/property-review",),
        rls_expectation="Platform Admin sees safe media projections; publication and retention services own canonical keys and processing state.",
        audit_expectation="Submission review and listing status events provide the business audit while media rows preserve immutable snapshots.",
        rationale="Responses expose URLs and metadata, never raw storage keys or generic media mutation.",
    ),
    "property_submission_media": _entry(
        domain="Private property-submission review media",
        sensitivity=(DataSensitivity.PRIVATE_MEDIA, DataSensitivity.STORAGE_KEY),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.SERVICE_MANAGED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/property-submissions",),
        ui_surfaces=("/dashboard/property-review",),
        rls_expectation="Platform Admin receives purpose-bound no-store signed access; processing/publication remains service-managed.",
        audit_expectation="Approval/rejection events cover the containing submission; media snapshots remain immutable.",
        rationale="Review access is sufficient without exposing or directly rewriting private canonical objects.",
    ),
    "property_submissions": _entry(
        domain="Property listing submissions and review",
        sensitivity=(DataSensitivity.CONTACT_PII,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/property-submissions",),
        ui_surfaces=("/dashboard/property-review",),
        rls_expectation="Only platform Admin reviews across owners and lines; submitters remain owner-scoped.",
        audit_expectation="Approval and rejection append reasoned audit entries.",
        rationale="Named review commands preserve RERA, media, ownership, and publication invariants.",
    ),
    "push_subscriptions": _entry(
        domain="Web-push device subscriptions",
        sensitivity=(DataSensitivity.PUSH_SECRET,),
        view_mode=AdminViewMode.PROHIBITED,
        view_coverage=CoverageState.PROTECTED,
        update_mode=AdminUpdateMode.SERVICE_MANAGED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.PROTECTED,
        rls_expectation="api_user has no table grants; only the authenticated subscribe/unsubscribe bypass service handles secrets.",
        audit_expectation="Raw endpoint and key material never enters audit records.",
        rationale="Admin has no legitimate need to read reusable browser endpoints or cryptographic subscription material.",
    ),
    "referral_bonus_config": _entry(
        domain="Referral bonus rules",
        sensitivity=(DataSensitivity.FINANCIAL,),
        view_mode=AdminViewMode.FULL,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.CONFIGURATION_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.GAP,
        api_surfaces=("/api/v1/referral-bonus-config",),
        ui_surfaces=("/dashboard/referral-rules",),
        rls_expectation="Platform Admin may manage all rules; Sub Admin remains creator-scoped.",
        audit_expectation="Create and correction commands affecting future accruals need append-only history.",
        rationale="Current rules are mutable financial configuration without a complete audit-log record.",
        gap="Gap: referral-rule create/update actions are not comprehensively represented in audit_log.",
    ),
    "referral_codes": _entry(
        domain="Client referral codes",
        sensitivity=(DataSensitivity.IDENTITY_PII,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.SERVICE_MANAGED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/referrals/admin",),
        ui_surfaces=("/dashboard/referral-payouts",),
        rls_expectation="Platform Admin sees codes only with authorized referral rows; issuance remains deterministic service work.",
        audit_expectation="The stable source record and referral conversion/payout history provide traceability.",
        rationale="Admin oversight needs attribution context but not arbitrary code reassignment or regeneration.",
    ),
    "referrals": _entry(
        domain="Referral attribution, accrual, and payout",
        sensitivity=(DataSensitivity.CONTACT_PII, DataSensitivity.FINANCIAL),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/referrals/admin",),
        ui_surfaces=("/dashboard/referral-payouts",),
        rls_expectation="Platform Admin sees masked referrals and may raise payouts; raw mobile and direct row writes stay unavailable.",
        audit_expectation="Immutable attribution/status linkage plus the audited payout workflow provides traceability.",
        rationale="The server derives recipient, amount, and idempotency key rather than accepting them from Admin.",
    ),
    "refresh_tokens": _entry(
        domain="Refresh-token rotation state",
        sensitivity=(DataSensitivity.SESSION_SECRET,),
        view_mode=AdminViewMode.PROHIBITED,
        view_coverage=CoverageState.PROTECTED,
        update_mode=AdminUpdateMode.SERVICE_MANAGED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.PROTECTED,
        rls_expectation="Session services own hash lookup, rotation, reuse detection, and revocation; no Admin read endpoint exists.",
        audit_expectation="Security events record outcomes without token hashes or raw session material.",
        rationale="Admin status/deletion commands revoke sessions but must never browse or mutate token records directly.",
    ),
    "site_visits": _entry(
        domain="Client property site-visit requests",
        sensitivity=(DataSensitivity.CONTACT_PII, DataSensitivity.PRECISE_LOCATION),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.PROHIBITED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/operations/site-visits",),
        ui_surfaces=("/dashboard/operations",),
        rls_expectation="Platform Admin may read through RLS; booking and cancellation remain Client-owned commands.",
        audit_expectation="The source request and audited vehicle-arrangement lifecycle provide operational history.",
        rationale="The paginated Admin projection provides scheduling context without contact, message, or pickup-location data.",
    ),
    "staff_feature_grants": _entry(
        domain="Delegated Sub Admin feature grants",
        view_mode=AdminViewMode.FULL,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.CONFIGURATION_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/staff-access",),
        ui_surfaces=("/dashboard/users",),
        rls_expectation="Platform Admin grants only closed supported features to eligible active staff.",
        audit_expectation="Grant and revoke append safe events and invalidate target sessions.",
        rationale="The closed catalogue prevents arbitrary privilege creation.",
    ),
    "staff_profiles": _entry(
        domain="Admin, Sub Admin, Telecaller, and Employee profiles",
        sensitivity=(DataSensitivity.IDENTITY_PII,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.STATUS_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/users", "/api/v1/admin/staff-access"),
        ui_surfaces=("/dashboard/users",),
        rls_expectation="Only platform Admin receives cross-line staff oversight; both-line staff never receive platform bypass.",
        audit_expectation="Provision, status, and feature changes append reasoned events.",
        rationale="Supported commands control access without arbitrary role, identity, or line rewrites.",
    ),
    "support_tickets": _entry(
        domain="Support and account-recovery tickets",
        sensitivity=(DataSensitivity.CONTACT_PII, DataSensitivity.IDENTITY_PII),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/support-tickets",),
        ui_surfaces=("/dashboard/support-tickets",),
        rls_expectation="Platform Admin owns triage; requesters remain owner-scoped and managed mobile-change tickets use their dedicated workflow.",
        audit_expectation="Every Admin transition appends support_ticket_advanced with safe detail.",
        rationale="Typed states and managed-workflow separation prevent support text from becoming an identity bypass.",
    ),
    "task_documents": _entry(
        domain="Employee-collected task documents",
        sensitivity=(
            DataSensitivity.KYC,
            DataSensitivity.PRIVATE_MEDIA,
            DataSensitivity.STORAGE_KEY,
        ),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/document-verification",),
        ui_surfaces=("/dashboard/document-verification",),
        rls_expectation="Platform Admin verifies through command-specific RLS; assigned Employees retain bounded collection access.",
        audit_expectation="Verification changes append document events without content or storage keys.",
        rationale="Signed downloads and explicit verification preserve assignment and private-document boundaries.",
    ),
    "task_feedback_media": _entry(
        domain="Assigned Employee property-visit feedback media",
        sensitivity=(DataSensitivity.PRIVATE_MEDIA, DataSensitivity.STORAGE_KEY),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.SERVICE_MANAGED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/tasks/{task_id}/feedback-media",),
        ui_surfaces=("/dashboard/admin-tasks",),
        rls_expectation="Platform Admin receives no-store signed access; assigned Employees alone create/delete within the task lifecycle.",
        audit_expectation="The immutable media row and parent task lifecycle provide provenance; keys stay out of audit output.",
        rationale="Admin can review sanitized evidence without acquiring upload or deletion authority.",
    ),
    "tasks": _entry(
        domain="Employee field and document tasks",
        sensitivity=(DataSensitivity.IDENTITY_PII,),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.SERVICE_MANAGED,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/tasks",),
        ui_surfaces=("/dashboard/admin-tasks",),
        rls_expectation="Platform Admin lists relationships read-only; Employees remain restricted to their assigned tasks.",
        audit_expectation="Every automatic assignment appends an employee_work_assigned system event.",
        rationale="A protected cursor owns assignment while Admin retains minimized workflow oversight.",
    ),
    "transactions": _entry(
        domain="Retained financial transaction ledger",
        sensitivity=(DataSensitivity.FINANCIAL, DataSensitivity.IDENTITY_PII),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.IMMUTABLE,
        update_coverage=CoverageState.PROTECTED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/operations/transactions",),
        ui_surfaces=("/dashboard/operations",),
        rls_expectation="Platform Admin may select through RLS; api_user has no write grant and producers append through controlled money services.",
        audit_expectation="Immutable ledger references and payout/commission/cashback/referral events provide traceability.",
        rationale="The paginated Admin projection exposes reconciliation context while excluding external and retained references.",
    ),
    "vehicle_arrangements": _entry(
        domain="Site-visit vehicle fulfilment",
        sensitivity=(DataSensitivity.CONTACT_PII, DataSensitivity.PRECISE_LOCATION),
        view_mode=AdminViewMode.MINIMIZED,
        view_coverage=CoverageState.COVERED,
        update_mode=AdminUpdateMode.WORKFLOW_COMMAND,
        update_coverage=CoverageState.COVERED,
        audit_coverage=CoverageState.COVERED,
        api_surfaces=("/api/v1/admin/vehicle-arrangements",),
        ui_surfaces=("/dashboard/vehicle-arrangements",),
        rls_expectation="Platform Admin fulfils logistics without choosing an assignee; the assigned Employee has bounded completion/cancellation commands.",
        audit_expectation="Every status or logistics transition appends vehicle_arrangement_updated without locations or contacts.",
        rationale="The dedicated state machine preserves Client ownership and assignment separation.",
    ),
}


# Explicit mapping of every noun in SRS FR-2.2 to its current storage spine.
# "record" intentionally spans the whole registry; the narrower nouns provide
# reviewable anchors for the requirement's named operational areas.
FR_2_2_DOMAIN_TABLES: dict[str, tuple[str, ...]] = {
    "record": tuple(ADMIN_OPERATIONAL_COVERAGE),
    "user": ("auth_users", "client_profiles", "agent_profiles", "staff_profiles"),
    "workflow": (
        "agent_applications",
        "leads",
        "lead_activities",
        "loan_applications",
        "loan_txn_history",
        "tasks",
        "property_submissions",
        "property_deals",
        "site_visits",
        "vehicle_arrangements",
        "support_tickets",
        "mobile_change_requests",
        "payouts",
    ),
    "product": ("loan_types",),
    "listing": (
        "properties",
        "property_media",
        "property_submissions",
        "property_submission_media",
    ),
    "bank": ("banks", "bank_loan_type_availability"),
    "banner": ("banners",),
    "offer": ("offers",),
    "referral": ("referral_codes", "referrals", "referral_bonus_config"),
    "notification": ("notifications", "push_subscriptions"),
    "report": ("leads", "loan_applications", "property_deals", "agent_profiles"),
}


def confirmed_gap_tables() -> frozenset[str]:
    """Return tables with a proven view, update, or audit gap."""

    return frozenset(
        table_name
        for table_name, entry in ADMIN_OPERATIONAL_COVERAGE.items()
        if CoverageState.GAP in {entry.view_coverage, entry.update_coverage, entry.audit_coverage}
    )
