"""baseline user table

Revision ID: 114766dba120
Revises:
Create Date: 2026-06-27 17:11:46.472484

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "114766dba120"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types manually
    role_enum = sa.dialects.postgresql.ENUM(
        "admin", "sub_admin", "agent", "telecaller", "employee", "client", name="role_enum"
    )
    role_enum.create(op.get_bind())
    business_line_enum = sa.dialects.postgresql.ENUM(
        "loans", "real_estate", "both", name="business_line_enum"
    )
    business_line_enum.create(op.get_bind())
    status_enum = sa.dialects.postgresql.ENUM(
        "active", "suspended", "pending_password_reset", "soft_deleted", name="status_enum"
    )
    status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("previous_user_id", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("mobile", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column(
            "role",
            sa.dialects.postgresql.ENUM(
                "admin",
                "sub_admin",
                "agent",
                "telecaller",
                "employee",
                "client",
                name="role_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "business_line",
            sa.dialects.postgresql.ENUM(
                "loans", "real_estate", "both", name="business_line_enum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.dialects.postgresql.ENUM(
                "active",
                "suspended",
                "pending_password_reset",
                "soft_deleted",
                name="status_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(role IN ('agent', 'telecaller', 'employee') "
            "AND business_line IN ('loans', 'real_estate')) "
            "OR (role IN ('admin', 'sub_admin', 'client') "
            "AND business_line IN ('loans', 'real_estate', 'both'))",
            name=op.f("ck_users_business_line_by_role"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_users_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_mobile"), "users", ["mobile"], unique=True)
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_mobile"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###

    # Drop enum types manually
    sa.dialects.postgresql.ENUM(name="role_enum").drop(op.get_bind())
    sa.dialects.postgresql.ENUM(name="business_line_enum").drop(op.get_bind())
    sa.dialects.postgresql.ENUM(name="status_enum").drop(op.get_bind())
