"""baseline user table

Revision ID: 114766dba120
Revises:
Create Date: 2026-06-27 17:11:46.472484

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "114766dba120"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types manually
    role_enum = sa.dialects.postgresql.ENUM(
        "admin", "sub_admin", "agent", "telecaller", "employee", "client", name="role_enum"
    )
    role_enum.create(op.get_bind())
    business_line_enum = sa.dialects.postgresql.ENUM(
        "loans", "real_estate", "both", name="business_line_enum"
    )
    business_line_enum.create(op.get_bind())
    status_enum = sa.dialects.postgresql.ENUM(
        "active", "suspended", "pending_password_reset", "soft_deleted", name="status_enum"
    )
    status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("mobile", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.dialects.postgresql.ENUM(
                "active",
                "suspended",
                "pending_password_reset",
                "soft_deleted",
                name="status_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_auth_user_uuid", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_auth_user_uuid"],
            ["auth_users.id"],
            name=op.f("fk_auth_users_created_by_auth_user_uuid_auth_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_users")),
    )
    op.create_index(op.f("ix_auth_users_mobile"), "auth_users", ["mobile"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_users_mobile"), table_name="auth_users")
    op.drop_table("auth_users")
    # ### end Alembic commands ###

    # Drop enum types manually
    sa.dialects.postgresql.ENUM(name="role_enum").drop(op.get_bind())
    sa.dialects.postgresql.ENUM(name="business_line_enum").drop(op.get_bind())
    sa.dialects.postgresql.ENUM(name="status_enum").drop(op.get_bind())
